# fly.toml app configuration file generated for evs-production on 2023-11-19T12:41:31-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "evs"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "node ./other/sentry-create-release"

[env]
  TZ = "US/Arizona"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/resources/healthcheck"
    protocol = "http"
